### ISSUE TITLE
Unfinished vault integration breaks other plugins.

### ISSUE THREAD

**Issue by LlmDl** [broccolai/tags#2]
The way that you've integrated vault [here](https://github.com/broccolai/tags/blob/f0b6e737b2da58f447a37ac9ec451a38db6acc16/src/main/java/broccolai/tags/integrations/VaultIntegration.java#L35) has made it so that other plugins which call on a permission plugin to supply methods like getGroupInfoInteger(), they will receive 0 instead of a valid response.

Notably, anyone using Towny will not be able to claim any plots while your plugin is present, because of the issue above.

Please correct this.

**Comment by broccolai** [comment]
Thanks

**Comment by LlmDl** [comment]
Very nice, your responsiveness is most excellent.
